Layout/EndOfLine:
  EnforcedStyle: lf

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": ()
    "%w": ()
    "%W": ()

# Style/TrailingCommaInHashLiteral:
#   Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false
