Layout/EndOfLine:
  EnforcedStyle: lf

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template
 
Lint/AmbiguousBlockAssociation:
  Enabled: false
